AM - Lidar Calculations Library, Radius Calculation function
IcebergASV/prop_mapper pull request #12
Opened 2024-01-20 18:50 UTC by adamm08

Created and tested the lidar calculations library with the radius calculation function. Test node and launch file included in /test directory.

2024-01-23 00:32 UTC, gpearcey requested changes
Can you do a short page in Gitbook with the link to the calculator site used, any other helpful references and a brief explanation of the math (just enough detail that jordan or I could figure it out after reading for example).

2024-01-23 00:32 UTC, gpearcey commented on lib/lidar_calculations.cpp
> +lidarCalculations::lidarCalculations() {}
C++ automatically generates a constructor, so unless you want to do something specific in the constructor, you can remove this.

2024-01-23 00:32 UTC, gpearcey commented on lib/lidar_calculations.cpp
> +        ROS_WARN("At least 6 points are required to calculate the radius of a cylinder.");
Replace "6" in the warning string with min_pnts.

2024-01-23 00:32 UTC, gpearcey commented on lib/lidar_calculations.cpp
> +        // mA_31 = mA_13
Can these comments be removed?

2024-01-24 22:21 UTC, adamm08 commented
Made all recommended changes.

2024-01-24 23:02 UTC, gpearcey approved these changes
GTM

2024-01-24 23:04 UTC, merged