updated radius checking
IcebergASV/prop_mapper pull request #20
Opened 2024-02-06 14:05 UTC by adamm08

[Asana Task](https://app.asana.com/0/home/1205672867564575/1206490635178371)

Updated radius checking to validate for the correct prop type rather than against any prop type.
Updated params to reflect each prop type.
Set prop type to buoy_lg or buoy_sm, if they fit the expected radius.

2024-02-08 00:46 UTC, gpearcey requested changes

2024-02-08 00:46 UTC, gpearcey commented on src/distance_finder.cpp
> +        if (prop_angles_msg_.prop_label == "red_marker" || prop_angles_msg_.prop_label == "green_marker") {
instead of repeating the if statements could you use the label to set an expected radius and expected radius range and then just check against the expected once?

2024-02-08 00:46 UTC, gpearcey commented on src/distance_finder.cpp
> +        if ((prop_label == "red_buoy" || prop_label == "green_buoy" || prop_label == "yellow_buoy")) {
Add debug for original and assigned label if checking for small and large

2024-02-08 01:41 UTC, gpearcey requested changes

2024-02-08 01:41 UTC, gpearcey commented on src/distance_finder.cpp
> +            if (radius>buoy_radius_lg_p-buoy_lg_radius_range_p && radius<buoy_radius_lg_p+buoy_lg_radius_range_p) {
The two if statements following the !check_small_buoys check can be `if else` instead of `if`.

2024-02-08 01:41 UTC, gpearcey commented on src/distance_finder.cpp
> +            if (radius>buoy_radius_lg_p-buoy_lg_radius_range_p && radius<buoy_radius_lg_p+buoy_lg_radius_range_p) {
I think you need to add `check_small_buoys` as a condition for the assigning small or large states if statements.

2024-02-08 05:30 UTC, adamm08 reviewed
all good now i think

2024-02-08 17:07 UTC, gpearcey requested changes

2024-02-08 17:07 UTC, gpearcey commented on src/distance_finder.cpp
> +            ROS_WARN_STREAM(TAG << "Calculated radius does not match expected " << prop_angles_msg_.prop_label << " radius");
Can we move this print statement to the validateRadius function so we can print the expected and calculated radius values in the statement?

2024-02-09 14:35 UTC, gpearcey approved these changes

2024-02-09 14:38 UTC, merged